{% set name = "sid-dev" %}
{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sid-dev-{{ version }}.tar.gz
  sha256: dbb77fa8d54dba2210d0abebd50b326ac7d5760ccd573aeacdc609155fae4377

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bokeh
    - dask
    - fastparquet
    - numba >=0.48
    - numpy
    - pandas >=1
    - python >=3.6
    - python-snappy
    - seaborn
    - tqdm

test:
  imports:
    - sid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/covid-19-impact-lab/sid
  summary: Simulate the spread of COVID-19 with different policies.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/covid-19-impact-lab/sid
  doc_url: https://sid-dev.readthedocs.io/

extra:
  recipe-maintainers:
    - tobiasraabe
    - roecla
    - janosg
